---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 3389, host: 3389 }]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[bastion]
    attributes:
  - name: chef-11
    run_list:
      - recipe[bastion]
    attributes:
    provisioner:
      require_chef_omnibus: 11.16.4
      client_rb:
        no_lazy_load: true
